/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Administrator' at '17-5-9 下午7:02' with Gradle 3.2.1
 *
 * @author Administrator, @date 17-5-9 下午7:02
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
